version: '3'

services:

  database:
    image: mariadb
    restart: unless-stopped
    networks:
      - wordpress-internal
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql

  php:
    build: .
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - traefikpress
      - wordpress-internal
    environment:
      DB_HOST: database
      DB_NAME: ${DB_NAME}
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      WP_HOME: ${WP_HOME}
      WP_SITEURL: ${WP_SITEURL}
    volumes:
      - ./:/code
      - ./config/docker/php.ini:/usr/local/etc/php/conf.d/bedrock.ini

  wordpress:
    image: nginx
    restart: unless-stopped
    depends_on:
      - php
    links:
      - php
    networks:
      - traefikpress
      - wordpress-internal
    labels:
      traefik.backend: "${DEV_WP}"
      traefik.docker.network: "traefikpress"
      traefik.frontend.rule: "Host:${DEV_WP}"
      traefik.enable: "true"
      traefik.port: "80"
    volumes:
      - ./:/code
      - ./config/docker/site.nginx.conf:/etc/nginx/conf.d/site.nginx.conf

networks:
  traefikpress:
    external: true
  wordpress-internal:
    driver: bridge
